apiVersion: fe.milung.eu/v1
kind: WebComponent
metadata:
  name: xmichalikl-ambulance-ufe
spec:
  module-uri: http://xmichalikl-ambulance-ufe.wac-hospital/build/wac-ufe.esm.js
                     # module web komponentu pre tento mikroFE
                     # - umiestnený v namespace wac-hospital
  navigation:
    - element: xmichalikl-ambulance-wl-list    # element, ktorý bude vložený na stránku
                                    # pri navigácii na zoznam čakajúcich
      path: xmichalikl-ambulance-wl      # cesta, ktora sa zobrazi v address bare v prehliadaci, ked bude tento mikroFE aktívny
      title: Zoznam čakajúcich xmichalikl      # názov mikro aplikácie
      details: Spravuje zoznam pacientov čakajúcich na vyšetrenie v ambulancii
  preload: false                    # určuje, či má byť web komponent načítaný spolu s hlavnou stránkou
  proxy: true                       # pre komponenty v rámci klastra, neprístupné na verejnej sieti
                                    # musí byť táto hodnota nastavená na true
  hash-suffix: v1alpha1             # voliteľný suffix pre načítanie modulu web komponentu - jeho zmenou
                                    # sa mení názov URL pre modul a tým je možné predísť problémom
                                    # s verziami vo vyrovnávacích pamätiach